import { MigrationInterface, QueryRunner } from "typeorm";

export class BaselineSchema1000000000000 implements MigrationInterface {
    name = 'BaselineSchema1000000000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "sessions" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "token" character varying(500) NOT NULL, "ip_address" character varying(45), "user_agent" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_e9f62f5dcb8a54b84234c9e7a06" UNIQUE ("token"), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_085d540d9f418cfbdc7bd55bb1" ON "sessions" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e9f62f5dcb8a54b84234c9e7a0" ON "sessions" ("token") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" SERIAL NOT NULL, "module" character varying(100) NOT NULL, "action" character varying(50) NOT NULL, "description" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_35ddf0f00aaedd9b4bd19f1f49" ON "permissions" ("module", "action") `);
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "description" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("user_id" integer NOT NULL, "role_id" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_23ed6f04fe43066df08379fd034" PRIMARY KEY ("user_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "username" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "created_by" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fe0bb3f6520ee0469504521e71" ON "users" ("username") `);
        await queryRunner.query(`CREATE TABLE "torretas" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "description" character varying(500), "external_id" character varying(255), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_9daf28dcfb4b712261c1247c675" UNIQUE ("external_id"), CONSTRAINT "PK_d866caa03ab564870cf79423fb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "torreta_colors" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "html_color" character varying(7) NOT NULL, "device_color_id" character varying(10) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_ad75c8b03881dc1b82dfc5872c4" UNIQUE ("name"), CONSTRAINT "PK_258b5b1ccc9c16c99dd93add8cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ad75c8b03881dc1b82dfc5872c" ON "torreta_colors" ("name") `);
        await queryRunner.query(`CREATE TABLE "raw_signals" ("id" SERIAL NOT NULL, "external_id" character varying(255) NOT NULL, "value" character varying(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ef43303d2c5f8cd6bea7788b5de" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dd85ddc3a07a2ba9f9151f5ae0" ON "raw_signals" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ca8a4e72a5aeaa8abb913b226" ON "raw_signals" ("external_id") `);
        await queryRunner.query(`CREATE TABLE "receptors" ("id" SERIAL NOT NULL, "external_id" character varying(255) NOT NULL, "name" character varying(255) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_741976319eb6c7c258c5c79e463" UNIQUE ("external_id"), CONSTRAINT "PK_6b102542cbaa660d10c6f52bc81" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_741976319eb6c7c258c5c79e46" ON "receptors" ("external_id") `);
        await queryRunner.query(`CREATE TABLE "processed_signals" ("id" SERIAL NOT NULL, "device_id" integer, "device_name" character varying(255), "device_signal_id" integer, "device_signal_name" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_97accfdf819bbf5a0174cd8186a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_93b54ef1d9226919b1a8cd9fde" ON "processed_signals" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_5c108156ae29b9097b74edfdb3" ON "processed_signals" ("device_signal_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_dce23dfb71368c6c946557f704" ON "processed_signals" ("device_id") `);
        await queryRunner.query(`CREATE TABLE "raw_measurements" ("id" SERIAL NOT NULL, "external_id" character varying(255) NOT NULL, "value" character varying(255) NOT NULL, "virtual_device" boolean NOT NULL DEFAULT false, "reason" character varying(255), "comment" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f7b6011852c0d461d7b611cbd30" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_86e1fec57e8de37b5dcfbe456e" ON "raw_measurements" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_4abffbc4e6ffb091fe6c709dcd" ON "raw_measurements" ("external_id") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" integer NOT NULL, "permission_id" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE TABLE "message_groups" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "color" character varying(7) NOT NULL, "description" character varying(255) NOT NULL, "order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_4c2ab511d6f33545f79966c7f8b" UNIQUE ("name"), CONSTRAINT "PK_d1b23101a05f540c1f9f5c7150f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4c2ab511d6f33545f79966c7f8" ON "message_groups" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."measurements_type_enum" AS ENUM('temperature', 'humidity', 'dew_point', 'ppm', 'pressure', 'level', 'flow', 'vibration', 'status')`);
        await queryRunner.query(`CREATE TABLE "measurements" ("id" SERIAL NOT NULL, "external_id" character varying(255) NOT NULL, "name" character varying(255) NOT NULL, "type" "public"."measurements_type_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_3c0e7812563f27fd68e8271661b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "measurement_values" ("id" SERIAL NOT NULL, "measurement_id" integer NOT NULL, "value" character varying(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_4c1097399c7fca441d0a1da10bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2264dcb86ec1f11aeda90acc35" ON "measurement_values" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_e95444731f8bd9ed4dd30c019f" ON "measurement_values" ("measurement_id") `);
        await queryRunner.query(`CREATE TABLE "areas" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_5110493f6342f34c978c084d0d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "departments" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "html_color" character varying(7), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "device_signals" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "device_id" integer NOT NULL, "department_id" integer NOT NULL, "external_value_id" character varying(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_342891b4b8b3c855caa741eefab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5ac17ff4517bf7b7b7ed963259" ON "device_signals" ("external_value_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d7a1571e860158fb67e485b74c" ON "device_signals" ("department_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_74346cf864661ab7ab828b91d0" ON "device_signals" ("device_id") `);
        await queryRunner.query(`CREATE TABLE "devices" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "area_id" integer NOT NULL, "external_id" character varying(255) NOT NULL, "is_virtual_device" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_a5f9c9ea439843d910175526ca9" UNIQUE ("external_id"), CONSTRAINT "PK_b1514758245c12daf43486dd1f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a5f9c9ea439843d910175526ca" ON "devices" ("external_id") `);
        await queryRunner.query(`CREATE TYPE "public"."events_status_enum" AS ENUM('open', 'in-progress', 'closed')`);
        await queryRunner.query(`CREATE TABLE "events" ("id" SERIAL NOT NULL, "area_id" integer NOT NULL, "area_name" character varying(255) NOT NULL, "department_id" integer NOT NULL, "department_name" character varying(255) NOT NULL, "device_id" integer NOT NULL, "device_name" character varying(255) NOT NULL, "device_signal_id" integer NOT NULL, "device_signal_name" character varying(255) NOT NULL, "status" "public"."events_status_enum" NOT NULL DEFAULT 'open', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "in_progress_at" TIMESTAMP WITH TIME ZONE, "closed_at" TIMESTAMP WITH TIME ZONE, "duration_seconds" integer, "virtual_device" boolean NOT NULL DEFAULT false, "reason" character varying(255), "comment" text, CONSTRAINT "PK_40731c7151fe4be3116e45ddf73" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7ebab07668bb225b6a04782a7d" ON "events" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_03dcebc1ab44daa177ae9479c4" ON "events" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_56d8f7a41dccbdf84daceca22e" ON "events" ("device_id", "device_signal_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_451bbcd8d5b2291c714f287704" ON "events" ("area_id", "department_id") `);
        await queryRunner.query(`CREATE TABLE "emails" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_a54dcebef8d05dca7e839749571" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "dashboard_measurement_groups" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "chart_time_range" integer, "chart_min_value" numeric(10,2), "chart_max_value" numeric(10,2), "chart_measurement_ids" jsonb, "chart2_time_range" integer, "chart2_min_value" numeric(10,2), "chart2_max_value" numeric(10,2), "chart2_measurement_ids" jsonb, "dashboard_measurement_order" jsonb, CONSTRAINT "PK_3e29d56265beb83ccef56456138" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "dashboard_measurements" ("id" SERIAL NOT NULL, "measurement_id" integer NOT NULL, "group_id" integer, "min_value" numeric(10,2) NOT NULL, "max_value" numeric(10,2) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_6a745bca803863b74cdbb73f3cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."area_torreta_configs_configuration_type_enum" AS ENUM('area', 'department')`);
        await queryRunner.query(`CREATE TABLE "area_torreta_configs" ("id" SERIAL NOT NULL, "area_id" integer NOT NULL, "torreta_external_id" character varying(255) NOT NULL, "configuration_type" "public"."area_torreta_configs_configuration_type_enum" NOT NULL DEFAULT 'area', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_a572cdf64e107b5760c8e2e2cc9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3c64b80558cc8acf5faeace99e" ON "area_torreta_configs" ("area_id", "torreta_external_id") `);
        await queryRunner.query(`CREATE TABLE "area_downtime_events" ("id" SERIAL NOT NULL, "area_downtime_id" integer NOT NULL, "event_id" integer NOT NULL, "added_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_146b0ce2d2c12006fe7c08a3be3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d9db4daf7eb6bcd7a5c15627df" ON "area_downtime_events" ("event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d1d081d3635a744e1dbc474145" ON "area_downtime_events" ("area_downtime_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d46062d2e3da26b0c2954ba3fe" ON "area_downtime_events" ("area_downtime_id", "event_id") `);
        await queryRunner.query(`CREATE TABLE "area_downtimes" ("id" SERIAL NOT NULL, "area_id" integer NOT NULL, "start_at" TIMESTAMP WITH TIME ZONE NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "ends_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_4a859704ff188213ab0ebc9f112" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9c5466e08a808d7f905bd69ddb" ON "area_downtimes" ("start_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_cf1714e4bbc4dd45a16dff2d1a" ON "area_downtimes" ("area_id", "start_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_3801e0557569bd118e745688f2" ON "area_downtimes" ("area_id", "is_active") `);
        await queryRunner.query(`CREATE TYPE "public"."alert_messages_message_type_enum" AS ENUM('torreta', 'receptor', 'email')`);
        await queryRunner.query(`CREATE TABLE "alert_messages" ("id" SERIAL NOT NULL, "alert_rule_id" integer NOT NULL, "message_type" "public"."alert_messages_message_type_enum" NOT NULL, "target_id" character varying(255) NOT NULL, "message" text NOT NULL, "color" character varying(10), "message_group_id" integer NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_91104b28b5e7270b1f458baf29d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4a4e49ddf951730b1c738d67f0" ON "alert_messages" ("message_group_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_80ca17694ec7a8b9cc594e85dc" ON "alert_messages" ("alert_rule_id") `);
        await queryRunner.query(`CREATE TYPE "public"."alert_rules_mode_enum" AS ENUM('setpoint', 'window')`);
        await queryRunner.query(`CREATE TABLE "alert_rules" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "measurement_id" integer NOT NULL, "mode" "public"."alert_rules_mode_enum" NOT NULL, "operator" character varying(10), "setpoint" numeric(10,2), "min_value" numeric(10,2), "max_value" numeric(10,2), "is_enabled" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_ae580564f087ffab9d229225aec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1ddba8ccca45992666cb6df5b4" ON "alert_rules" ("is_enabled") `);
        await queryRunner.query(`CREATE INDEX "IDX_da336467c8ec98e4bbea00d3a1" ON "alert_rules" ("measurement_id") `);
        await queryRunner.query(`CREATE TABLE "alert_triggers" ("id" SERIAL NOT NULL, "alert_rule_id" integer NOT NULL, "raw_measurement_id" integer NOT NULL, "measurement_value" numeric(10,2) NOT NULL, "condition_result" character varying(500) NOT NULL, "messages_triggered" jsonb NOT NULL, "triggered_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8a7ba06f20359a3ed5a86f5c3fc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0c3572311eb8de37ddfe5d3f5a" ON "alert_triggers" ("triggered_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_1136cfe7c51a69bc96e330fa61" ON "alert_triggers" ("raw_measurement_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f3bf362170aa0b64fda5224996" ON "alert_triggers" ("alert_rule_id") `);
        await queryRunner.query(`CREATE TABLE "alert_escalation_configs" ("id" SERIAL NOT NULL, "device_id" integer NOT NULL, "device_signal_id" integer NOT NULL, "endpoint_url" character varying(500) NOT NULL DEFAULT 'http://localhost:1880/events', "warning_delay_minutes" integer NOT NULL DEFAULT '20', "escalation1_delay_minutes" integer NOT NULL DEFAULT '40', "escalation2_delay_minutes" integer NOT NULL DEFAULT '60', "escalation3_delay_minutes" integer NOT NULL DEFAULT '80', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_79c8239b424123e404468573736" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c9b642a4086e6363cab0901e1b" ON "alert_escalation_configs" ("device_id", "device_signal_id") `);
        await queryRunner.query(`CREATE TYPE "public"."alert_escalation_messages_level_enum" AS ENUM('alert', 'warning', 'escalation1', 'escalation2', 'escalation3', 'close')`);
        await queryRunner.query(`CREATE TYPE "public"."alert_escalation_messages_message_type_enum" AS ENUM('torreta', 'receptor', 'email')`);
        await queryRunner.query(`CREATE TABLE "alert_escalation_messages" ("id" SERIAL NOT NULL, "escalation_config_id" integer NOT NULL, "level" "public"."alert_escalation_messages_level_enum" NOT NULL, "message_type" "public"."alert_escalation_messages_message_type_enum" NOT NULL, "target_id" character varying(255) NOT NULL, "message" text NOT NULL, "color" character varying(10), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_b849470c357b3797f22aa9b2f79" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2d02d63d98c6af79dc5a726086" ON "alert_escalation_messages" ("escalation_config_id", "level") `);
        await queryRunner.query(`CREATE TYPE "public"."event_alert_logs_level_enum" AS ENUM('alert', 'warning', 'escalation1', 'escalation2', 'escalation3', 'close')`);
        await queryRunner.query(`CREATE TABLE "event_alert_logs" ("id" SERIAL NOT NULL, "event_id" integer NOT NULL, "level" "public"."event_alert_logs_level_enum" NOT NULL, "sent_at" TIMESTAMP WITH TIME ZONE NOT NULL, "messages_sent" jsonb NOT NULL, "success" boolean NOT NULL, "error_message" text, "endpoint_url" character varying(500) NOT NULL, CONSTRAINT "PK_ef2286c9cc4bcdd5d8fca16c5a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4c56ae856a134f5813650f8682" ON "event_alert_logs" ("sent_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_f1aacd16d718156f031d723c8c" ON "event_alert_logs" ("event_id", "level") `);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "measurement_values" ADD CONSTRAINT "FK_e95444731f8bd9ed4dd30c019f9" FOREIGN KEY ("measurement_id") REFERENCES "measurements"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "device_signals" ADD CONSTRAINT "FK_74346cf864661ab7ab828b91d00" FOREIGN KEY ("device_id") REFERENCES "devices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "device_signals" ADD CONSTRAINT "FK_d7a1571e860158fb67e485b74c1" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "devices" ADD CONSTRAINT "FK_91080dacf9231b7c3839480669d" FOREIGN KEY ("area_id") REFERENCES "areas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_7f3b739a288133551e2df419b90" FOREIGN KEY ("area_id") REFERENCES "areas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_f4e9377ad537819a7d8de9f225f" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_677f1dbebfe5223c39d15f229ef" FOREIGN KEY ("device_id") REFERENCES "devices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_d74bf9f2580adc55d9ccdee6e6e" FOREIGN KEY ("device_signal_id") REFERENCES "device_signals"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dashboard_measurements" ADD CONSTRAINT "FK_2456ed5ee32bef9d660e48c76ae" FOREIGN KEY ("measurement_id") REFERENCES "measurements"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dashboard_measurements" ADD CONSTRAINT "FK_2bb0061b7a024dd22808392f835" FOREIGN KEY ("group_id") REFERENCES "dashboard_measurement_groups"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "area_downtime_events" ADD CONSTRAINT "FK_d1d081d3635a744e1dbc474145c" FOREIGN KEY ("area_downtime_id") REFERENCES "area_downtimes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "area_downtime_events" ADD CONSTRAINT "FK_d9db4daf7eb6bcd7a5c15627df9" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "area_downtimes" ADD CONSTRAINT "FK_cfa5642b0f902bcff97cc510dc0" FOREIGN KEY ("area_id") REFERENCES "areas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alert_messages" ADD CONSTRAINT "FK_80ca17694ec7a8b9cc594e85dc5" FOREIGN KEY ("alert_rule_id") REFERENCES "alert_rules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alert_messages" ADD CONSTRAINT "FK_4a4e49ddf951730b1c738d67f0f" FOREIGN KEY ("message_group_id") REFERENCES "message_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alert_rules" ADD CONSTRAINT "FK_da336467c8ec98e4bbea00d3a1d" FOREIGN KEY ("measurement_id") REFERENCES "measurements"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alert_triggers" ADD CONSTRAINT "FK_f3bf362170aa0b64fda52249967" FOREIGN KEY ("alert_rule_id") REFERENCES "alert_rules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alert_triggers" ADD CONSTRAINT "FK_1136cfe7c51a69bc96e330fa613" FOREIGN KEY ("raw_measurement_id") REFERENCES "raw_measurements"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alert_escalation_configs" ADD CONSTRAINT "FK_999c32cef1e577fce2fe641937f" FOREIGN KEY ("device_id") REFERENCES "devices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alert_escalation_configs" ADD CONSTRAINT "FK_2f21064dae7fb9293aa9fc3a1cb" FOREIGN KEY ("device_signal_id") REFERENCES "device_signals"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alert_escalation_messages" ADD CONSTRAINT "FK_380ffe6dcafcc59bca79c47356c" FOREIGN KEY ("escalation_config_id") REFERENCES "alert_escalation_configs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_alert_logs" ADD CONSTRAINT "FK_154124e1291122eafe7baaba518" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "event_alert_logs" DROP CONSTRAINT "FK_154124e1291122eafe7baaba518"`);
        await queryRunner.query(`ALTER TABLE "alert_escalation_messages" DROP CONSTRAINT "FK_380ffe6dcafcc59bca79c47356c"`);
        await queryRunner.query(`ALTER TABLE "alert_escalation_configs" DROP CONSTRAINT "FK_2f21064dae7fb9293aa9fc3a1cb"`);
        await queryRunner.query(`ALTER TABLE "alert_escalation_configs" DROP CONSTRAINT "FK_999c32cef1e577fce2fe641937f"`);
        await queryRunner.query(`ALTER TABLE "alert_triggers" DROP CONSTRAINT "FK_1136cfe7c51a69bc96e330fa613"`);
        await queryRunner.query(`ALTER TABLE "alert_triggers" DROP CONSTRAINT "FK_f3bf362170aa0b64fda52249967"`);
        await queryRunner.query(`ALTER TABLE "alert_rules" DROP CONSTRAINT "FK_da336467c8ec98e4bbea00d3a1d"`);
        await queryRunner.query(`ALTER TABLE "alert_messages" DROP CONSTRAINT "FK_4a4e49ddf951730b1c738d67f0f"`);
        await queryRunner.query(`ALTER TABLE "alert_messages" DROP CONSTRAINT "FK_80ca17694ec7a8b9cc594e85dc5"`);
        await queryRunner.query(`ALTER TABLE "area_downtimes" DROP CONSTRAINT "FK_cfa5642b0f902bcff97cc510dc0"`);
        await queryRunner.query(`ALTER TABLE "area_downtime_events" DROP CONSTRAINT "FK_d9db4daf7eb6bcd7a5c15627df9"`);
        await queryRunner.query(`ALTER TABLE "area_downtime_events" DROP CONSTRAINT "FK_d1d081d3635a744e1dbc474145c"`);
        await queryRunner.query(`ALTER TABLE "dashboard_measurements" DROP CONSTRAINT "FK_2bb0061b7a024dd22808392f835"`);
        await queryRunner.query(`ALTER TABLE "dashboard_measurements" DROP CONSTRAINT "FK_2456ed5ee32bef9d660e48c76ae"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "FK_d74bf9f2580adc55d9ccdee6e6e"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "FK_677f1dbebfe5223c39d15f229ef"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "FK_f4e9377ad537819a7d8de9f225f"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "FK_7f3b739a288133551e2df419b90"`);
        await queryRunner.query(`ALTER TABLE "devices" DROP CONSTRAINT "FK_91080dacf9231b7c3839480669d"`);
        await queryRunner.query(`ALTER TABLE "device_signals" DROP CONSTRAINT "FK_d7a1571e860158fb67e485b74c1"`);
        await queryRunner.query(`ALTER TABLE "device_signals" DROP CONSTRAINT "FK_74346cf864661ab7ab828b91d00"`);
        await queryRunner.query(`ALTER TABLE "measurement_values" DROP CONSTRAINT "FK_e95444731f8bd9ed4dd30c019f9"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1aacd16d718156f031d723c8c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c56ae856a134f5813650f8682"`);
        await queryRunner.query(`DROP TABLE "event_alert_logs"`);
        await queryRunner.query(`DROP TYPE "public"."event_alert_logs_level_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d02d63d98c6af79dc5a726086"`);
        await queryRunner.query(`DROP TABLE "alert_escalation_messages"`);
        await queryRunner.query(`DROP TYPE "public"."alert_escalation_messages_message_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."alert_escalation_messages_level_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9b642a4086e6363cab0901e1b"`);
        await queryRunner.query(`DROP TABLE "alert_escalation_configs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3bf362170aa0b64fda5224996"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1136cfe7c51a69bc96e330fa61"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0c3572311eb8de37ddfe5d3f5a"`);
        await queryRunner.query(`DROP TABLE "alert_triggers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da336467c8ec98e4bbea00d3a1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ddba8ccca45992666cb6df5b4"`);
        await queryRunner.query(`DROP TABLE "alert_rules"`);
        await queryRunner.query(`DROP TYPE "public"."alert_rules_mode_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_80ca17694ec7a8b9cc594e85dc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a4e49ddf951730b1c738d67f0"`);
        await queryRunner.query(`DROP TABLE "alert_messages"`);
        await queryRunner.query(`DROP TYPE "public"."alert_messages_message_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3801e0557569bd118e745688f2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf1714e4bbc4dd45a16dff2d1a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c5466e08a808d7f905bd69ddb"`);
        await queryRunner.query(`DROP TABLE "area_downtimes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d46062d2e3da26b0c2954ba3fe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1d081d3635a744e1dbc474145"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d9db4daf7eb6bcd7a5c15627df"`);
        await queryRunner.query(`DROP TABLE "area_downtime_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c64b80558cc8acf5faeace99e"`);
        await queryRunner.query(`DROP TABLE "area_torreta_configs"`);
        await queryRunner.query(`DROP TYPE "public"."area_torreta_configs_configuration_type_enum"`);
        await queryRunner.query(`DROP TABLE "dashboard_measurements"`);
        await queryRunner.query(`DROP TABLE "dashboard_measurement_groups"`);
        await queryRunner.query(`DROP TABLE "emails"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_451bbcd8d5b2291c714f287704"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_56d8f7a41dccbdf84daceca22e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_03dcebc1ab44daa177ae9479c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ebab07668bb225b6a04782a7d"`);
        await queryRunner.query(`DROP TABLE "events"`);
        await queryRunner.query(`DROP TYPE "public"."events_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a5f9c9ea439843d910175526ca"`);
        await queryRunner.query(`DROP TABLE "devices"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_74346cf864661ab7ab828b91d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d7a1571e860158fb67e485b74c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5ac17ff4517bf7b7b7ed963259"`);
        await queryRunner.query(`DROP TABLE "device_signals"`);
        await queryRunner.query(`DROP TABLE "departments"`);
        await queryRunner.query(`DROP TABLE "areas"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e95444731f8bd9ed4dd30c019f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2264dcb86ec1f11aeda90acc35"`);
        await queryRunner.query(`DROP TABLE "measurement_values"`);
        await queryRunner.query(`DROP TABLE "measurements"`);
        await queryRunner.query(`DROP TYPE "public"."measurements_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c2ab511d6f33545f79966c7f8"`);
        await queryRunner.query(`DROP TABLE "message_groups"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4abffbc4e6ffb091fe6c709dcd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_86e1fec57e8de37b5dcfbe456e"`);
        await queryRunner.query(`DROP TABLE "raw_measurements"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dce23dfb71368c6c946557f704"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c108156ae29b9097b74edfdb3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93b54ef1d9226919b1a8cd9fde"`);
        await queryRunner.query(`DROP TABLE "processed_signals"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_741976319eb6c7c258c5c79e46"`);
        await queryRunner.query(`DROP TABLE "receptors"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ca8a4e72a5aeaa8abb913b226"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd85ddc3a07a2ba9f9151f5ae0"`);
        await queryRunner.query(`DROP TABLE "raw_signals"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad75c8b03881dc1b82dfc5872c"`);
        await queryRunner.query(`DROP TABLE "torreta_colors"`);
        await queryRunner.query(`DROP TABLE "torretas"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe0bb3f6520ee0469504521e71"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35ddf0f00aaedd9b4bd19f1f49"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9f62f5dcb8a54b84234c9e7a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_085d540d9f418cfbdc7bd55bb1"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
    }

}
